/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;


/**
 *
 * @author User
 */
public class Grammateia extends javax.swing.JFrame {

    /**
     * Creates new form Grammateia
     */
    private Model.Grammateia grammateia = null;
    public Grammateia() {
        initComponents();
        
        Stoixeia_Grammateia sg = new Stoixeia_Grammateia();
        jDesktopPane1.add(sg).setVisible(true);
    }

    public Grammateia(Model.Grammateia grammateia) {
        initComponents();
        this.grammateia = grammateia;
        jDesktopPane1.removeAll();
        Stoixeia_Grammateia sk = new Stoixeia_Grammateia();
        jDesktopPane1.add(sk).setVisible(true);
    }
    
    static boolean maximized = true;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MovePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ButtonMinimize = new javax.swing.JPanel();
        Minimize1 = new javax.swing.JLabel();
        ButtonExit = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        jPanel_Left = new javax.swing.JPanel();
        Stoixeia = new javax.swing.JPanel();
        Stoixeia_G = new javax.swing.JLabel();
        Programma_Spoudwn = new javax.swing.JPanel();
        Programma_Spoudwn_G = new javax.swing.JLabel();
        Dhlwseis = new javax.swing.JPanel();
        Dhlwseis_G = new javax.swing.JLabel();
        Diorthotikes = new javax.swing.JPanel();
        Diorthotikes_Vathmologies_G1 = new javax.swing.JLabel();
        Log_out = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MovePanel.setBackground(new java.awt.Color(60, 63, 65));
        MovePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovePanelMouseDragged(evt);
            }
        });
        MovePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovePanelMousePressed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Untitled-1.jpg"))); // NOI18N

        ButtonMinimize.setBackground(new java.awt.Color(60, 63, 65));
        ButtonMinimize.setForeground(new java.awt.Color(255, 51, 102));

        Minimize1.setBackground(new java.awt.Color(255, 255, 255));
        Minimize1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Minimize1.setForeground(new java.awt.Color(255, 255, 255));
        Minimize1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/minimize_window_50px.png"))); // NOI18N
        Minimize1.setMaximumSize(new java.awt.Dimension(20, 20));
        Minimize1.setMinimumSize(new java.awt.Dimension(20, 20));
        Minimize1.setPreferredSize(new java.awt.Dimension(30, 30));
        Minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Minimize1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Minimize1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Minimize1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout ButtonMinimizeLayout = new javax.swing.GroupLayout(ButtonMinimize);
        ButtonMinimize.setLayout(ButtonMinimizeLayout);
        ButtonMinimizeLayout.setHorizontalGroup(
            ButtonMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Minimize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ButtonMinimizeLayout.setVerticalGroup(
            ButtonMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonMinimizeLayout.createSequentialGroup()
                .addComponent(Minimize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ButtonExit.setBackground(new java.awt.Color(60, 63, 65));

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_window_50px.png"))); // NOI18N
        Exit.setMaximumSize(new java.awt.Dimension(20, 20));
        Exit.setMinimumSize(new java.awt.Dimension(20, 20));
        Exit.setPreferredSize(new java.awt.Dimension(20, 20));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ButtonExitLayout = new javax.swing.GroupLayout(ButtonExit);
        ButtonExit.setLayout(ButtonExitLayout);
        ButtonExitLayout.setHorizontalGroup(
            ButtonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonExitLayout.createSequentialGroup()
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        ButtonExitLayout.setVerticalGroup(
            ButtonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonExitLayout.createSequentialGroup()
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MovePanelLayout = new javax.swing.GroupLayout(MovePanel);
        MovePanel.setLayout(MovePanelLayout);
        MovePanelLayout.setHorizontalGroup(
            MovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MovePanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 754, Short.MAX_VALUE)
                .addComponent(ButtonMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MovePanelLayout.setVerticalGroup(
            MovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MovePanelLayout.createSequentialGroup()
                .addGroup(MovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(ButtonMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(MovePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 30));

        jPanel_Left.setBackground(new java.awt.Color(204, 204, 204));

        Stoixeia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stoixeia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StoixeiaMouseClicked(evt);
            }
        });

        Stoixeia_G.setText("Στοιχεία Γραμματείας");

        javax.swing.GroupLayout StoixeiaLayout = new javax.swing.GroupLayout(Stoixeia);
        Stoixeia.setLayout(StoixeiaLayout);
        StoixeiaLayout.setHorizontalGroup(
            StoixeiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StoixeiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Stoixeia_G, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        StoixeiaLayout.setVerticalGroup(
            StoixeiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StoixeiaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(Stoixeia_G, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Programma_Spoudwn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Programma_Spoudwn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Programma_SpoudwnMouseClicked(evt);
            }
        });

        Programma_Spoudwn_G.setText("Πρόγραμμα Σπουδών");

        javax.swing.GroupLayout Programma_SpoudwnLayout = new javax.swing.GroupLayout(Programma_Spoudwn);
        Programma_Spoudwn.setLayout(Programma_SpoudwnLayout);
        Programma_SpoudwnLayout.setHorizontalGroup(
            Programma_SpoudwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Programma_SpoudwnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Programma_Spoudwn_G, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        Programma_SpoudwnLayout.setVerticalGroup(
            Programma_SpoudwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Programma_SpoudwnLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(Programma_Spoudwn_G, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Dhlwseis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dhlwseis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DhlwseisMouseClicked(evt);
            }
        });

        Dhlwseis_G.setText("Δηλώσεις");

        javax.swing.GroupLayout DhlwseisLayout = new javax.swing.GroupLayout(Dhlwseis);
        Dhlwseis.setLayout(DhlwseisLayout);
        DhlwseisLayout.setHorizontalGroup(
            DhlwseisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DhlwseisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dhlwseis_G, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        DhlwseisLayout.setVerticalGroup(
            DhlwseisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DhlwseisLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(Dhlwseis_G, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Diorthotikes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Diorthotikes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiorthotikesMouseClicked(evt);
            }
        });

        Diorthotikes_Vathmologies_G1.setText("Έγκρισεις  Βαθμολογίας");
        Diorthotikes_Vathmologies_G1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Diorthotikes_Vathmologies_G1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DiorthotikesLayout = new javax.swing.GroupLayout(Diorthotikes);
        Diorthotikes.setLayout(DiorthotikesLayout);
        DiorthotikesLayout.setHorizontalGroup(
            DiorthotikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiorthotikesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Diorthotikes_Vathmologies_G1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DiorthotikesLayout.setVerticalGroup(
            DiorthotikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiorthotikesLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(Diorthotikes_Vathmologies_G1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Log_out.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Αποσύνδεση");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Log_outLayout = new javax.swing.GroupLayout(Log_out);
        Log_out.setLayout(Log_outLayout);
        Log_outLayout.setHorizontalGroup(
            Log_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Log_outLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Log_outLayout.setVerticalGroup(
            Log_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_LeftLayout = new javax.swing.GroupLayout(jPanel_Left);
        jPanel_Left.setLayout(jPanel_LeftLayout);
        jPanel_LeftLayout.setHorizontalGroup(
            jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stoixeia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Programma_Spoudwn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Dhlwseis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Log_out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Diorthotikes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_LeftLayout.setVerticalGroup(
            jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LeftLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(Stoixeia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Programma_Spoudwn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dhlwseis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Diorthotikes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(Log_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel_Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int x,y;
    private void StoixeiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StoixeiaMouseClicked
        jDesktopPane1.removeAll();
        Stoixeia_Grammateia sg = new Stoixeia_Grammateia();
        jDesktopPane1.add(sg).setVisible(true);
    }//GEN-LAST:event_StoixeiaMouseClicked

    private void Programma_SpoudwnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Programma_SpoudwnMouseClicked
        jDesktopPane1.removeAll();
        Programma_Spoudwn ps = new Programma_Spoudwn();
        jDesktopPane1.add(ps).setVisible(true);
    }//GEN-LAST:event_Programma_SpoudwnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //systemExit();
        //Login_Form l = new Login_Form();
        //l.setVisible(true);
        this.toBack();
        setVisible(false);
        new Login_Form().toFront();
        new Login_Form().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DiorthotikesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiorthotikesMouseClicked
        
    }//GEN-LAST:event_DiorthotikesMouseClicked

    private void Diorthotikes_Vathmologies_G1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Diorthotikes_Vathmologies_G1MouseClicked
        jDesktopPane1.removeAll();
        View.Diorthosi_Vathmologias_K dv = null;
        try {
            dv = new Diorthosi_Vathmologias_K();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Grammateia.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(dv).setVisible(true);
    }//GEN-LAST:event_Diorthotikes_Vathmologies_G1MouseClicked

    private void MovePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_MovePanelMouseDragged
    private int xMouse, yMouse;
    private void MovePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_MovePanelMousePressed

    private void Minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize1MouseClicked
        this.setState(1);
    }//GEN-LAST:event_Minimize1MouseClicked
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    private void Minimize1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize1MouseEntered
        changecolor(ButtonMinimize, new Color(25, 29, 74));
    }//GEN-LAST:event_Minimize1MouseEntered

    private void Minimize1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize1MouseExited
        changecolor(ButtonMinimize, new Color(60,63,65));
    }//GEN-LAST:event_Minimize1MouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        changecolor(ButtonExit, new Color(25, 29, 74));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        changecolor(ButtonExit, new Color(60,63,65));
    }//GEN-LAST:event_ExitMouseExited

    private void DhlwseisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DhlwseisMouseClicked
        jDesktopPane1.removeAll();
        Dilwseis_G d = new Dilwseis_G();
        jDesktopPane1.add(d).setVisible(true);
    }//GEN-LAST:event_DhlwseisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grammateia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grammateia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grammateia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grammateia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grammateia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonExit;
    private javax.swing.JPanel ButtonMinimize;
    private javax.swing.JPanel Dhlwseis;
    private javax.swing.JLabel Dhlwseis_G;
    private javax.swing.JPanel Diorthotikes;
    private javax.swing.JLabel Diorthotikes_Vathmologies_G1;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel Log_out;
    private javax.swing.JLabel Minimize1;
    private javax.swing.JPanel MovePanel;
    private javax.swing.JPanel Programma_Spoudwn;
    private javax.swing.JLabel Programma_Spoudwn_G;
    private javax.swing.JPanel Stoixeia;
    private javax.swing.JLabel Stoixeia_G;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_Left;
    // End of variables declaration//GEN-END:variables
}
