/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.List;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;



import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class Stoixeia_Kathigiti extends javax.swing.JInternalFrame {

    /**
     * Creates new form Stoixeia_Kathigiti
     */
    public Stoixeia_Kathigiti() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    public void loadDefaultValues(Model.Kathigitis kathigitis)
    {
        name.setText(kathigitis.getOnoma());
        speciality.setText(kathigitis.getEidikotita());
        Email.setText(kathigitis.getEmail());
        dig_sign.setText(""+kathigitis.getDigital_signature()+"");
    }
    
    public Stoixeia_Kathigiti(Model.Kathigitis kathigitis) {
        initComponents();
        this.loadDefaultValues(kathigitis);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Stoixeia_K = new javax.swing.JLabel();
        onoma = new javax.swing.JLabel();
        eidikothta = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        digital_signature = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        speciality = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        dig_sign = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 490));

        Stoixeia_K.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Stoixeia_K.setText("Στοιχεία Καθηγητή:");

        onoma.setText("'Ονομα:");

        eidikothta.setText("Ειδικότητα:");

        email.setText("Email:");

        digital_signature.setText("Digital Signature:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Stoixeia_K)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(onoma)
                        .addGap(18, 18, 18)
                        .addComponent(name))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eidikothta)
                        .addGap(18, 18, 18)
                        .addComponent(speciality))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(email)
                        .addGap(18, 18, 18)
                        .addComponent(Email))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(digital_signature)
                        .addGap(18, 18, 18)
                        .addComponent(dig_sign)))
                .addContainerGap(567, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Stoixeia_K)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onoma)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eidikothta)
                    .addComponent(speciality))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(Email))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dig_sign)
                    .addComponent(digital_signature))
                .addContainerGap(335, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Stoixeia_K;
    private javax.swing.JLabel dig_sign;
    private javax.swing.JLabel digital_signature;
    private javax.swing.JLabel eidikothta;
    private javax.swing.JLabel email;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel onoma;
    private javax.swing.JLabel speciality;
    // End of variables declaration//GEN-END:variables
}
